# 默认配置文件

# 应用程序配置
app:
  name: "Codebase Knowledge Builder"
  version: "0.1.0"
  debug: false

# LLM 配置
llm:
  provider: "openai"  # 可选: openai, openrouter, alibaba, volcengine, moonshot
  model: "gpt-4"
  max_tokens: 4000
  temperature: 0.7

  # OpenAI 配置
  openai:
    base_url: "https://api.openai.com/v1"

  # OpenRouter 配置
  openrouter:
    base_url: "https://openrouter.ai/api/v1"
    app_url: "http://localhost:3000"
    app_name: "Codebase Knowledge Builder"

  # 阿里百炼配置
  alibaba:
    base_url: "https://dashscope.aliyuncs.com/api/v1"

  # 火山引擎配置
  volcengine:
    base_url: "https://api.volcengine.com/ml/api/v1/services"
    service_id: ""  # 需要在环境变量中设置

  # 硅基流动配置
  moonshot:
    base_url: "https://api.moonshot.cn/v1"

# Langfuse 配置
langfuse:
  enabled: true
  host: "https://cloud.langfuse.com"
  project_name: "codebase-knowledge-builder"

# Git 仓库配置
git:
  default_branch: "main"
  cache_ttl: 86400  # 24小时，单位：秒
  max_commits: 100

# 节点配置
nodes:
  analyze_history:
    max_commits: 100
    include_file_history: true
    analyze_contributors: true
    summary_prompt_template: |
      你是一个代码库历史分析专家。请分析以下 Git 提交历史，并提供一个全面的总结。

      提交历史:
      {commit_history}

      贡献者信息:
      {contributors}

      请提供以下内容:
      1. 代码库的总体发展历程和主要里程碑
      2. 主要贡献者及其贡献领域
      3. 代码库的主要模块和组件（基于提交信息推断）
      4. 代码库的开发模式和协作方式
      5. 任何其他有价值的见解

      请以 Markdown 格式输出，使用适当的标题、列表和强调。
